export const sampleProducts = [
  {
    id: "1",
    name: "Laptop",
    price: 999.99,
    data: {
      color: "Silver",
      capacity: "512GB SSD",
      brand: "Dell",
      Generation: "10th Gen",
      "Screen size": '15.6"',
      "CPU model": "Intel i7",
    },
  },
  {
    id: "2",
    name: "Smartphone",
    price: 699.99,
    data: {
      color: null,
      capacity: "256GB",
      brand: "Apple",
      "Strap Colour": "Midnight Blue",
      "Case Size": "Medium",
    },
  },
  {
    id: "3",
    name: "Desk Chair",
    price: 199.99,
    data: {
      color: "Brown",
      capacity: null,
      brand: "IKEA",
      Description: "Ergonomic design",
    },
  },
  {
    id: "4",
    name: "Monitor",
    price: 249.99,
    data: {
      color: "Black",
      "Screen size": "27-inch",
      brand: null,
      "Hard disk size": null,
    },
  },
  {
    id: "5",
    name: "Keyboard",
    price: 89.99,
    data: null,
  },
  {
    id: "6",
    name: "Mouse",
    price: 49.99,
    data: {
      color: null,
      capacity: "Wireless",
      brand: "Razer",
      "Strap Colour": "Black",
    },
  },
  {
    id: "7",
    name: "Headphones",
    price: 129.99,
    data: {
      color: "Blue",
      capacity: null,
      brand: "Sony",
      Description: "Noise Cancelling",
    },
  },
  {
    id: "8",
    name: "Tablet",
    price: 329.99,
    data: {
      color: "Space Gray",
      capacity: "128GB",
      brand: null,
      "CPU model": "A14 Bionic",
    },
  },
  {
    id: "9",
    name: "Smart Watch",
    price: 199.99,
    data: {
      color: "Midnight",
      capacity: null,
      brand: "Samsung",
      "Strap Colour": "Black",
    },
  },
  {
    id: "10",
    name: "Printer",
    price: 149.99,
    data: {
      color: "White",
      capacity: "All-in-One",
      brand: "HP",
      Generation: null,
    },
  },
  {
    id: "11",
    name: "External SSD",
    price: 119.99,
    data: {
      color: "Silver",
      capacity: "1TB",
      brand: null,
      "Hard disk size": "1TB",
    },
  },
  {
    id: "12",
    name: "Webcam",
    price: 79.99,
    data: {
      color: "Black",
      capacity: null,
      brand: "Logitech",
      "Screen size": "1080p",
    },
  },
  {
    id: "13",
    name: "Microphone",
    price: 99.99,
    data: {
      color: null,
      capacity: "Cardioid",
      brand: "Blue",
      Description: "Studio quality",
    },
  },
  {
    id: "14",
    name: "Router",
    price: 89.99,
    data: {
      color: "Black",
      capacity: "Wi-Fi 6",
      brand: "TP-Link",
      generation: null,
    },
  },
  {
    id: "15",
    name: "Power Bank",
    price: 39.99,
    data: {
      color: "Red",
      capacity: "10000mAh",
      brand: null,
      "Case Size": "Compact",
    },
  },
  {
    id: "16",
    name: "USB Hub",
    price: 29.99,
    data: {
      color: "Gray",
      capacity: null,
      brand: "Sabrent",
      "CPU model": null,
    },
  },
  {
    id: "17",
    name: "Desk Lamp",
    price: 59.99,
    data: {
      color: "White",
      capacity: "Adjustable",
      brand: null,
      Description: "LED Lighting",
    },
  },
  {
    id: "18",
    name: "Backpack",
    price: 49.99,
    data: {
      color: "Black",
      capacity: null,
      brand: "SwissGear",
      "Strap Colour": "Black",
    },
  },
  {
    id: "19",
    name: "Notebook",
    price: 9.99,
    data: {
      color: "Yellow",
      capacity: "College Ruled",
      brand: null,
      Generation: null,
    },
  },
  {
    id: "20",
    name: "Pen",
    price: 2.99,
    data: {
      color: "Blue",
      capacity: null,
      brand: "Pilot",
      Description: "Ballpoint",
    },
  },
  {
    id: "21",
    name: "Stapler",
    price: 12.99,
    data: {
      color: "Black",
      capacity: "Standard",
      brand: null,
      "Hard disk size": null,
    },
  },
  {
    id: "22",
    name: "Paper Shredder",
    price: 69.99,
    data: {
      color: "White",
      capacity: null,
      brand: "Fellowes",
      "Screen size": "8-Sheet",
    },
  },
  {
    id: "23",
    name: "Calculator",
    price: 19.99,
    data: {
      color: "Silver",
      capacity: "Scientific",
      brand: null,
      generation: "TI-84",
    },
  },
  {
    id: "24",
    name: "Whiteboard",
    price: 39.99,
    data: {
      color: "White",
      capacity: null,
      brand: "U Brands",
      "Case Size": "24x36 inches",
    },
  },
  {
    id: "25",
    name: "Sticky Notes",
    price: 4.99,
    data: {
      color: "Yellow",
      capacity: "3x3 inches",
      brand: null,
      Description: null,
    },
  },
]
